name: Build Incus RootFS List

on:
  workflow_dispatch:
  pull_request:
    branches: [deploy/incus]
  push:
    branches: [deploy/incus]
  schedule:
    # Run every day at 2:00 AM UTC
    - cron: '0 2 * * *'

jobs:
  build-incus-rootfs-list:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
      - name: Build incus images list
        shell: pwsh
        run: |
          .\hack\Invoke-IncusDistributionsBuild.ps1 incus.rootfs.json

      - name: Upload JSON metadata
        uses: actions/upload-artifact@v4
        with:
          name: ${{ hashFiles('incus.rootfs.json') }}
          path: "incus.rootfs.json"

  commit-incus-rootfs-list:
    runs-on: ubuntu-latest
    needs: build-incus-rootfs-list
    permissions:
      contents: write
    if: ${{ github.ref == 'refs/heads/deploy/incus' || github.event_name == 'schedule' }}
    steps:
      - name: Checkout rootfs branch
        uses: actions/checkout@v4
        with:
          ref: rootfs
      - uses: actions/download-artifact@v4
      - name: Commit incus.rootfs.json
        run: |
          cat */*.rootfs.json > incus.rootfs.json
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if git diff --quiet incus.rootfs.json; then
            echo "No changes to incus.rootfs.json"
          else
            echo "Changes detected in incus.rootfs.json, committing..."
            git add incus.rootfs.json
            git commit -m "Update incus.rootfs.json"
            git push
          fi
